Feature/forgot password register
UTN-FRBA-Mobile/Konzern pull request #9
Opened 2020-05-25 19:57 UTC by lucascharlab

## Resumen
 - [Breve resumen en puntos de lo que hiciste]
 
## Screenshots
 - [Algunas capturas de pantalla para mostrar lo que hiciste]

2020-05-25 22:45 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginFragment.kt
> +        }
Estos setters van en "onViewCreated"

2020-05-25 22:46 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginFragment.kt
>      }
No hace falta crear una interfaz nueva. Podés borrarla y utilizar LoginFragmentView :)

2020-05-25 22:47 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginFragment.kt
> +                    startActivity(intent)
Los cambios de Activity se tienen que dar desde la Activity que contiene a los Fragments. Podés usar la interfaz, fijate la función `successfulSignIn()`

2020-05-25 22:48 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginFragment.kt
> +                    ).show()
Los mensajes que se muestran deberían ser manejados desde la Activity, fijate que hice un par de ejemplos como `signInWithGoogleFailed()`

2020-05-25 22:50 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginActivity.kt
> +            // No backstack to pop, so calling super
Acá podés sacar este comentario, se entiende que no hay mas fragments en la stack.

2020-05-25 22:52 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +        view.vSingUpButton.setOnClickListener{ createAccount() }
Pasá estos setters a `onViewCreated`

2020-05-25 22:52 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +        auth = FirebaseAuth.getInstance()
Este podés pasarlo a `onCreate`

2020-05-25 22:53 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +    ): View? {
Acá podés resumirlo a `: View? = inflater.inflate(R.layout.fragment_sign_up, container, false)`

2020-05-25 22:56 UTC, NicoMedero commented on app/src/main/res/layout/login_fragment_layout.xml
> +        android:id="@+id/loginFragmentLayout">
Podés remover los  `xmlns`  porque el contenedor padre los posee.

2020-05-25 22:57 UTC, NicoMedero commented on app/src/main/res/layout/fragment_sign_up.xml
> +        xmlns:app="http://schemas.android.com/apk/res-auto">
Acá también podés sacar los `xmlns` porque el contenedor padre ya los posee

2020-05-25 23:09 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +            vSignUpEmail.error = "Complete este campo"
Los textos hay que setearlos en string.xml , podés llamarlos con `getString(R.string.<id_del_string>)`

2020-05-25 23:12 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +                    val user = auth.currentUser
Acá agregá un `//TODO: Usar este user para manejar la persistencia`

2020-05-25 23:13 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +                    startActivity(intent)
Lo mismo que con LoginFragment, es necesario que uses una interfaz que comunique a la Activity contenedora para que ejecute esta acción.

Además si no hacés un `finish()` , esta actividad va a quedar en la Stack.

Podés usar de ejemplo los métodos que ya están :)

2020-05-25 23:15 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +                        Toast.LENGTH_SHORT).show()
Acá también deberías decirle a la Activity que hubo un error y el texto podés setearlo en `string.xml`

2020-05-25 23:15 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +
Como comentario extra, podés agregar la interfaz acá y llamarla `SignUpView`

2020-05-25 23:16 UTC, NicoMedero commented on app/src/main/res/layout/fragment_sign_up.xml
> +            android:hint="@string/login_password_hint"
Este hint podría ser "Repeat Password"

2020-05-25 23:33 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +        }
Acá podemos aplicar un poco más de funcional y hacer asi:
```
return when {
            vSignUpEmail.text.isEmpty() -> {
                vSignUpEmail.error = "Complete este campo"
                false
            }
            !Patterns.EMAIL_ADDRESS.matcher(vSignUpEmail.text).matches() -> {
                vSignUpEmail.error = "Ingrese un Email válido"
                false
            }
            else -> {
                vSignUpEmail.error = null
                true
            }
        }
```

2020-05-25 23:33 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +        }
Acá también podemos agregarle un poco el lujo de funcional

```
return when {
            vSignUpPassword.text.toString() != vSignUpRepeatPassword.text.toString() -> {
                vSignUpPassword.error = "Las contraseñas no coinciden"
                vSignUpRepeatPassword.error = "Las contraseñas no coinciden"
                false
            }
            vSignUpPassword.text.toString().length < 6 -> {
                vSignUpPassword.error = "La contraseña debe tener más de 6 caracteres"
                false
            }
            else -> {
                vSignUpPassword.error = null
                vSignUpRepeatPassword.error = null
                true
            }
        }
```

2020-05-25 23:34 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +    }
Ahora que nuestras funciones de validar devuelven un boolean, podés reescribir esta función asi:

```
private fun validateForm(): Boolean {
        return validateEmail() && validatePasswords()
    }
```

2020-05-25 23:36 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +
En los Ifs , lo mejor es ir por el lado "true", así que yo cambiaría esto así:

```
if (validateForm()) {
            auth.createUserWithEmailAndPassword(vSignUpEmail.text.toString(), vSignUpPassword.text.toString())
                .addOnCompleteListener() { task ->
                    if (task.isSuccessful) {
                        val user = auth.currentUser
                        val intent = Intent(this.activity?.applicationContext, MainActivity::class.java)
                        startActivity(intent)
                    } else {
                        Toast.makeText(this.activity, task.exception?.message,
                            Toast.LENGTH_SHORT).show()
                    }
                }
        } else {
            // el formulario está mal
        }
```

2020-05-25 23:37 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +    private var formValid: Boolean = true
Hacer esto provoca SideEffect, no es una buena práctica.

Lo mejor es hacer que las funciones devuelvan true o false dependiendo del input o de la evaluación que hagan dentro.
Te muestro con unos ejemplos en tu código.

2020-05-25 23:38 UTC, NicoMedero requested changes
Es un buen PR!

No te desanimes por todos los comentarios que te hice, es para que mejores cada vez mas en el código!

Si hay algo que no entendés, lo vemos sin problemas.

2020-05-25 23:41 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/SignUpFragment.kt
> +    private var formValid: Boolean = true
Me refiero a `private var formValid: Boolean`

2020-06-02 19:22 UTC, lucascharlab commented
@NicoMedero no se por que, me dejó de funcionar una parte del signup y no logro descubrir por qué. cuando le pego a firebase, devuelva success o no, no se abre ningún toast ni se redirige a la pantalla de login en el caso del success.

2020-06-03 17:55 UTC, lucascharlab commented
@NicoMedero ya lo solucioné, si me das el ok lo mergeo

2020-06-05 05:44 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginFragment.kt
> +        }
no hace falta llamar a la `view` para referenciar a los botones. Directamente podés hacer `vLoginForgotMyPassword.setOnClickListener{ .. }`

2020-06-05 05:50 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/ForgotPasswordFragment.kt
> +    }
podemos volar este método porque no sobreescribimos nada :)

2020-06-05 05:51 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/ForgotPasswordFragment.kt
> +    }
Las interfaces deben estar declaradas al final de la clase, por convención

2020-06-05 05:56 UTC, NicoMedero commented on app/src/main/java/utn/frba/mobile/konzern/login/LoginActivity.kt
> +    }
La activity tiene que decidir qué fragment mostrar. Entonces a través de la interfaz vos le decís: "El usuario tocó el botón de SignUp o de ForgotPassword" y a raiz de eso la Activity overridea esos métodos y elige qué hacer.

Yo sé que es medio paja que el código se repita, pero no está bien que el fragment decida por la activity.

Deberían quedar dos métodos así:
```
override fun onSignUpButtonClicked() {
  ...
  transacción al fragment de SignUp
}

override fun onForgotPasswordButtonClicked() {
  ...
  transacción al fragment de ForgotPassword
}
```

2020-06-05 05:59 UTC, NicoMedero reviewed
Viene bien el PR, solo dejo unos comentarios

2020-06-07 02:54 UTC, merged